<<<<<<< HEAD
import type {  Risk  } from '../types/risk';
=======
import type { Risk } from '../types/risk';
>>>>>>> 1e4385f895625aba346926ef66dc3fd5520c4f70

export const initialMockRisks: Risk[] = [
  {
    id: 'r1',
    title: 'New Carbon Tax Legislation',
    description: 'Upcoming regional carbon tax legislation could significantly increase operational costs if emissions are not reduced by 20% in the next fiscal year.',
    category: 'Financial',
    department: 'Finance',
    owner: 'Sarah Connor',
    likelihood: 'Likely',
    impact: 'High',
    riskScore: 12,
    severity: 'High',
    status: 'Monitoring',
    mitigationPlan: 'Accelerate the transition to renewable energy sources for the primary manufacturing plant and explore carbon credits.',
    createdDate: '2026-05-10',
    reviewedDate: '2026-07-01',
  },
  {
    id: 'r2',
    title: 'Supply Chain Labor Violations',
    description: 'Potential for labor law violations in tier 2 suppliers located in emerging markets, leading to reputational damage and compliance fines.',
    category: 'Compliance',
    department: 'Procurement',
    owner: 'Jane Doe',
    likelihood: 'Possible',
    impact: 'Critical',
    riskScore: 16,
    severity: 'Critical',
    status: 'Identified',
    mitigationPlan: 'Implement mandatory third-party audits for all tier 1 and tier 2 suppliers. Update the supplier code of conduct.',
    createdDate: '2026-07-15',
  },
  {
    id: 'r3',
    title: 'Data Center Energy Outage',
    description: 'Extreme weather events could cause rolling blackouts affecting the primary data center, interrupting core services.',
    category: 'Operational',
    department: 'IT',
    owner: 'Alice Johnson',
    likelihood: 'Rare',
    impact: 'High',
    riskScore: 6,
    severity: 'Medium',
    status: 'Mitigated',
    mitigationPlan: 'Switched to a redundant multi-region cloud architecture and upgraded local backup generators.',
    createdDate: '2025-11-20',
    reviewedDate: '2026-06-15',
  },
  {
    id: 'r4',
    title: 'Greenwashing Allegations',
    description: 'Inconsistent sustainability reporting across regional branches could lead to public allegations of greenwashing.',
    category: 'Governance',
    department: 'Corporate Affairs',
    owner: 'Robert Brown',
    likelihood: 'Possible',
    impact: 'Medium',
    riskScore: 8,
    severity: 'Medium',
    status: 'Monitoring',
    mitigationPlan: 'Centralize all ESG reporting through the new EcoSphere platform to ensure data accuracy and consistency.',
    createdDate: '2026-03-05',
    reviewedDate: '2026-07-10',
  }
];
