import type {  AuditFinding  } from '../types/auditFinding';

export const initialMockAuditFindings: AuditFinding[] = [
  {
    id: 'af1',
    auditId: 'au1',
    auditName: 'Q3 Internal Environmental Audit',
    title: 'Incomplete Emissions Log',
    description: 'The monthly emissions log for the main manufacturing plant is missing entries for the last two weeks of July.',
    department: 'Manufacturing',
    severity: 'High',
    status: 'Open',
    assignedTo: 'John Smith',
    dueDate: '2026-08-30',
    identifiedDate: '2026-08-16',
  },
  {
    id: 'af2',
    auditId: 'au2',
    auditName: 'Supplier Code of Conduct Review',
    title: 'Supplier Y Labor Law Non-Compliance',
    description: 'Supplier Y was found to have irregularities in working hour logs, indicating potential violations of local labor laws.',
    department: 'Procurement',
    severity: 'Critical',
    status: 'Under Review',
    assignedTo: 'Jane Doe',
    dueDate: '2026-08-01',
    identifiedDate: '2026-07-22',
  },
  {
    id: 'af3',
    auditId: 'au3',
    auditName: 'Data Privacy Compliance Check',
    title: 'Unencrypted Customer Backups',
    description: 'A legacy database backup was found stored in an unencrypted S3 bucket.',
    department: 'IT',
    severity: 'Critical',
    status: 'Resolved',
    assignedTo: 'Alice Johnson',
    dueDate: '2026-06-20',
    identifiedDate: '2026-06-11',
    resolutionNotes: 'Bucket encryption enabled. Legacy backups securely migrated to the new vault and original files destroyed.',
  },
  {
    id: 'af4',
    auditId: 'au3',
    auditName: 'Data Privacy Compliance Check',
    title: 'Missing Consent Banners',
    description: 'Two regional marketing landing pages did not have the mandatory cookie consent banner.',
    department: 'Marketing',
    severity: 'Medium',
    status: 'Closed',
    assignedTo: 'Robert Brown',
    dueDate: '2026-06-30',
    identifiedDate: '2026-06-12',
    resolutionNotes: 'Marketing team updated the templates. Banner is now globally enforced via the CMS.',
  }
];
