import { ESGReport } from '../types/esgReport';

export const initialMockESGReports: ESGReport[] = [
  {
    id: 'esg1',
    title: 'Q2 2026 ESG Summary Report',
    reportType: 'ESG Summary',
    department: 'ESG Office',
    reportingPeriod: 'Q2 2026',
    createdBy: 'Sarah Connor',
    createdDate: '2026-07-10',
    status: 'Published',
    description: 'Comprehensive ESG performance summary covering environmental, social, and governance metrics for Q2 2026.',
    fileUrl: '/reports/q2-2026-esg-summary.pdf',
  },
  {
    id: 'esg2',
    title: 'H1 2026 Carbon Emissions Analysis',
    reportType: 'Carbon Report',
    department: 'Operations',
    reportingPeriod: 'H1 2026',
    createdBy: 'Alice Johnson',
    createdDate: '2026-07-08',
    status: 'Reviewed',
    description: 'Detailed analysis of Scope 1, 2, and 3 carbon emissions for the first half of 2026, including year-on-year comparisons.',
  },
  {
    id: 'esg3',
    title: 'Supplier Compliance Audit Report',
    reportType: 'Compliance Report',
    department: 'Procurement',
    reportingPeriod: 'Q2 2026',
    createdBy: 'Jane Doe',
    createdDate: '2026-07-05',
    status: 'Generated',
    description: 'Audit findings for 50 tier-1 and tier-2 suppliers against the updated Code of Conduct.',
  },
  {
    id: 'esg4',
    title: 'Annual Sustainability Report 2025',
    reportType: 'Sustainability Report',
    department: 'ESG Office',
    reportingPeriod: 'FY 2025',
    createdBy: 'Robert Brown',
    createdDate: '2026-06-15',
    status: 'Published',
    description: 'Annual sustainability report covering environmental stewardship, community engagement, and governance for FY 2025.',
    fileUrl: '/reports/annual-sustainability-2025.pdf',
  },
  {
    id: 'esg5',
    title: 'Q3 2026 ESG Draft Summary',
    reportType: 'ESG Summary',
    department: 'ESG Office',
    reportingPeriod: 'Q3 2026',
    createdBy: 'Sarah Connor',
    createdDate: '2026-07-12',
    status: 'Draft',
    description: 'Draft ESG summary in preparation for Q3 2026 reporting cycle.',
  },
];
